### ISSUE TITLE
This will never be null

### ISSUE THREAD

**Issue by FreezePhoenix** [Spadar/AdventureLand#1]
https://github.com/Spadar/AdventureLand/blob/master/Class%20Intro%20Scripts/Other%20Classes/Other.js#L125
Due to the way JS works, this would never be null. If a key does not exist in an object, and you attempt to access that key, it returns `undefined`, not `null`.
Please fix this in any related scripts.

**Comment by Spadar** [comment]
You can use != for null or undefined. In this case it works fine. 

undefined != null is false
null != null is false
"test" != null is true

This is only an issue if you use strict comparisons (!== or === for example).

**Comment by FreezePhoenix** [comment]
@Spadar Huh, just learned something there. Never thought this would be true:
```javascript
undefined == null
```
